import { reddit, scheduler } from '@devvit/web/server';
import type { Report, ReportJobData, ShadowDecision, SeniorDecision } from '../../shared/types.js';
import { MOD_ACTION_LABELS } from '../../shared/types.js';
import { incrementStats, updateShadowStatus, removePending, getShadowDecision, getSeniorDecisionsForPost } from './decisions.js';

export function buildReport(
  shadow: ShadowDecision,
  senior: SeniorDecision,
  finalAction: string,
  postTitle: string,
  postPermalink: string,
): Report {
  return {
    postId: shadow.postId,
    postTitle,
    postPermalink,
    shadow,
    senior,
    finalAction,
    agreement: shadow.action === senior.action,
    generatedAt: new Date().toISOString(),
  };
}

export function formatReportMessage(report: Report): string {
  const agreement = report.agreement ? '✅ Match' : '❌ Diverged';
  const shadowLabel  = MOD_ACTION_LABELS[report.shadow.action]  ?? report.shadow.action;
  const seniorLabel  = MOD_ACTION_LABELS[report.senior.action]  ?? report.senior.action;

  return [
    `**ShadowMod Report** — [${report.postTitle}](${report.postPermalink})`,
    '',
    `| | Decision | Reasoning |`,
    `|---|---|---|`,
    `| Your call | ${shadowLabel} | ${report.shadow.reason} |`,
    `| Senior mod | ${seniorLabel} | ${report.senior.reason} |`,
    `| Final outcome | ${report.finalAction} | — |`,
    '',
    `**Result:** ${agreement}`,
    '',
    report.agreement
      ? 'Your judgment matched the senior mod. Keep it up.'
      : `The senior mod chose differently. Review the community rules and discuss with your mentor if unclear.`,
    '',
    `_Generated by ShadowMod at ${new Date(report.generatedAt).toUTCString()}_`,
  ].join('\n');
}

export async function scheduleReport(data: ReportJobData): Promise<void> {
  await scheduler.runJob({
    name: 'generate-report',
    runAt: new Date(),
    data: data as unknown as Record<string, string>,
  });
}

export async function deliverReport(data: ReportJobData, subredditName: string): Promise<void> {
  const { postId, shadowModId, finalAction, postTitle, postPermalink } = data;

  const shadow = await getShadowDecision(postId, shadowModId);
  if (!shadow) return;

  const seniors = await getSeniorDecisionsForPost(postId);
  if (seniors.length === 0) return;
  const senior = seniors[seniors.length - 1]!;

  const report = buildReport(shadow, senior, finalAction, postTitle, postPermalink);
  const message = formatReportMessage(report);

  // Send as modmail to the shadow mod
  try {
    await reddit.sendPrivateMessage({
      to: shadow.shadowModName,
      subject: `ShadowMod: your decision on "${postTitle.slice(0, 60)}"`,
      text: message,
    });
  } catch {
    // Fallback: write as a mod note on the trainee
    await reddit.addModNote({
      subreddit: subredditName,
      user: shadow.shadowModName,
      note: `ShadowMod: your call was ${shadow.action}, senior chose ${senior.action}. ${report.agreement ? 'Match' : 'Diverged'}`,
    });
  }

  await incrementStats(shadowModId, report.agreement);
  await updateShadowStatus(postId, shadowModId, 'complete');
  await removePending(postId, shadowModId);
}
