import { reddit, scheduler } from '@devvit/web/server';
import type { Report, ReportJobData, ObserverDecision, ReviewerDecision } from '@/shared/types.js';
import { MOD_ACTION_LABELS } from '@/shared/types.js';
import {
  incrementStats,
  updateObserverStatus,
  removePending,
  getObserverDecision,
  getReviewerDecisionsForPost,
} from './decisions.js';

/**
 * Assembles a Comparison report from an Observer decision, a Reviewer decision,
 * and the final mod action that triggered report generation.
 *
 * Agreement is determined by action equality; reasoning differences are preserved
 * for the Observer to review in the delivered report.
 */
export function buildReport(
  observer: ObserverDecision,
  reviewer: ReviewerDecision,
  finalAction: string,
  postTitle: string,
  postPermalink: string,
): Report {
  return {
    postId: observer.postId,
    postTitle,
    postPermalink,
    observer,
    reviewer,
    finalAction,
    agreement: observer.action === reviewer.action,
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Renders a Comparison report as a Markdown message suitable for modmail.
 * Formats Observer vs Reviewer vs Outcome in a table with reasoning from both sides.
 */
export function formatReportMessage(report: Report): string {
  const agreement = report.agreement ? '✅ Match' : '❌ Diverged';
  const observerLabel = MOD_ACTION_LABELS[report.observer.action] ?? report.observer.action;
  const reviewerLabel = MOD_ACTION_LABELS[report.reviewer.action] ?? report.reviewer.action;

  return [
    `**ShadowMod Report**: [${report.postTitle}](${report.postPermalink})`,
    '',
    `| | Decision | Reasoning |`,
    `|---|---|---|`,
    `| Your call | ${observerLabel} | ${report.observer.reason} |`,
    `| Reviewer | ${reviewerLabel} | ${report.reviewer.reason} |`,
    `| Final outcome | ${report.finalAction} | N/A |`,
    '',
    `**Result:** ${agreement}`,
    '',
    report.agreement
      ? 'Your judgment matched the reviewer. Keep it up.'
      : `Your reviewer chose differently. Review the community rules and discuss with them if unclear.`,
    '',
    `_Generated by ShadowMod at ${new Date(report.generatedAt).toUTCString()}_`,
  ].join('\n');
}

/**
 * Enqueues a `generate-report` scheduler job to run immediately.
 * Scheduling rather than inline generation lets the trigger handler return quickly,
 * avoiding Devvit's tight trigger timeout.
 */
export async function scheduleReport(data: ReportJobData): Promise<void> {
  await scheduler.runJob({
    name: 'generate-report',
    runAt: new Date(),
    data: data as unknown as Record<string, string>,
  });
}

/**
 * Fetches the Observer and Reviewer decisions, builds the Comparison report,
 * and delivers it to the Observer via modmail.
 *
 * Falls back to a mod note if modmail is unavailable. Regardless of delivery
 * method, updates Observer stats and marks the decision as `complete`.
 * When multiple Reviewers exist for the post, the most recently added one is used.
 */
export async function generateReport(data: ReportJobData, subredditName: string): Promise<void> {
  const { postId, observerId, finalAction, postTitle, postPermalink } = data;

  const observer = await getObserverDecision(postId, observerId);
  if (!observer) return;

  const reviewers = await getReviewerDecisionsForPost(postId);
  if (reviewers.length === 0) return;
  const reviewer = reviewers[reviewers.length - 1]!;

  const report = buildReport(observer, reviewer, finalAction, postTitle, postPermalink);
  const message = formatReportMessage(report);

  try {
    await reddit.sendPrivateMessage({
      to: observer.observerName,
      subject: `ShadowMod: your decision on "${postTitle.slice(0, 60)}"`,
      text: message,
    });
  } catch {
    await reddit.addModNote({
      subreddit: subredditName,
      user: observer.observerName,
      note: `ShadowMod: your call was ${observer.action}, reviewer chose ${reviewer.action}. ${report.agreement ? 'Match' : 'Diverged'}`,
    });
  }

  await incrementStats(observerId, report.agreement);
  await updateObserverStatus(postId, observerId, 'complete');
  await removePending(postId, observerId);
}
